### ISSUE TITLE
Use prepared statements for queries

### ISSUE THREAD

**Issue by decden** [kiber42/wordfinder#1]
The codebase seems to be using string concatenation for passing parameters to queries. From a security standpoint this is usually bad practice (the strings are sanitized, but it is easy to make errors this way. By the way, ever wondered why the function is called `real_escape_string` instead of `escape_string`? Humans make mistakes).

The correct way to approach this is to use prepared statements, which separates the query from its input, which basically solves the problem of SQL injection:
https://www.php.net/manual/en/mysqli.quickstart.prepared-statements.php

**Comment by kiber42** [comment]
That is a very good suggestion! I hesitated to use prepared statements because I was unsure of the performance overhead, so I felt clever and went with `real_escape_string`. But you are right, sooner or later this will cause trouble and it's better to use security best practices already at an early stage. In addition, `real_escape_string` probably also does a database round-trip, so most likely using a prepared statement will not have a worse performance. I will switch to prepared statements as soon as possible. Thanks!

**Comment by kiber42** [comment]
Addressed in 178bb93 for all user-provided strings in SQL queries.
